### ISSUE TITLE
你把部分代码删掉了吗

### ISSUE THREAD

**Issue by Fly-Playgroud** [Great233/crawler#2]
请问你把部分代码删掉了吗？之前有关注到你这个项目，然后今天发现少了很多代码

**Comment by abtswath** [comment]
重构了，之前写的比较烂，现在大概基本的爬取完成了，剩下一些表单填充、事件触发的工作没做

**Comment by Fly-Playgroud** [comment]
哦哦可以，期待再次上线，我现在在维护rod中文API文档，希望可以有更多交流

**Comment by abtswath** [comment]
🤝

BUG-Fly ***@***.***>于2022年8月20日 周六10:52写道：
